[formatter.nixfmt]
command = "nixfmt"
includes = [
  "*.nix",
  "nix/*.nix",
]

[formatter.elisp]
command = "emacs"
options = [
  "--quick",
  "--batch",
  "--eval",
  "(progn (find-file (car command-line-args-left)) (emacs-lisp-mode) (indent-tabs-mode -1) (indent-region (point-min) (point-max)) (save-buffer))",
]
includes = [
  "*.el",
  "site-lisp/*.el",
  "recipes/*",
]

[formatter.org]
command = "emacs"
options = [
  "--quick",
  "--batch",
  "--eval",
  "(progn (find-file (car command-line-args-left)) (indent-tabs-mode -1) (setq org-src-content-indentation 0) (indent-region (point-min) (point-max)) (save-buffer))",
]
includes = [
  "*.org"
]
