[formatter.typos]
command = "typos"
options = ["--write-changes"]
includes = ["*.org", "*.nix", "*.el", "*.md", "*.toml"]
priority = 2

[formatter.nixfmt]
command = "nixfmt"
includes = [
  "*.nix",
  "nix/*.nix",
]
priority = 3

[formatter.elisp]
command = "emacs"
options = [
  "--batch",
  "--eval",
  "(progn (find-file (car command-line-args-left)) (emacs-lisp-mode) (setq make-backup-files nil version-control nil) (indent-tabs-mode -1) (indent-region (point-min) (point-max)) (save-buffer))",
]
includes = [
  "*.el",
  "site-lisp/*.el",
  "recipes/*",
]
priority = 4
